spring:
  application:
    name: greaming

  # 프로필 설정
  config:
    import: optional:classpath:application-local.yml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # AWS S3 설정
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: greaming-bucket
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
